version: '2.2'

services:
  rabbit:
    container_name: rabbitmq
    image: rabbitmq/rabbitmq:3.7.3-management
    build: ./rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    volumes:
      - rabbit-conf-storage:/etc/rabbitmq
      - rabbit-storage:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbit-tier

volumes:
  rabbit-conf-storage:
    driver: local
  rabbit-storage:
    driver: local

networks:
  rabbit-tier:
    driver: bridge
